name: CharacterTools
description:
  zh: "CharacterTools提供的对当前文档自然段落中区域文本的格式调整的工具，详细的功能列表如下所示："
  en: "CharacterTools provides tools for modifying the format of font in partial area. The detailed function list of this tool is as follows:"