name: ImageTools
description:
  zh: "ImageTools提供的阅读当前文档图片格式调整的工具，详细的功能列表如下所示："
  en: "ImageTools provides tools for modifying the format for image. The detailed function list of this tool is as follows:"