name: PageTools
description:
  zh: "PageTools提供的阅读当前文档页面格式调整的工具，详细的功能列表如下所示："
  en: "PageTools provides tools for modifying the format for page1. The detailed function list of this tool is as follows:"