name: TableTools
description:
  zh: "TableTools提供的对当前文档表格调整的工具，详细的功能列表如下所示："
  en: "TableTools provides tools for modifying the format for table. The detailed function list of this tool is as follows:"