name: TextTools
description:
  zh: "TextTools提供的对当前文档自然段落的段落格式和字体格式调整的工具，详细的功能列表如下所示："
  en: "TextTools provides tools for modifying the format for paragraph and font. The detailed function list of this tool is as follows:"